name: Go

on:
  pull_request:
    branches: 
        - main
        - develop

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19
        - name: Set up golangci-lint
          uses: golangci/golangci-lint-action@v3.2.0
          with:
            version: latest
            skip-cache: true
          
        - name: Run linter
          run: golangci-lint run
 
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19

        - name: Test
          run: go test -v ./...

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19

        - name: Build
          run: go build -v ./...
